# -*- coding: utf-8 -*-
"""Number_Guessing_Game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xaoepxvEK9FOtycwj60gg7S6BfJIM7h5
"""

import math
import random

low = int(input("Enter the lower bound : "))

high = int(input("Enter the upper bound : "))

num = random.randint(low,high)

chance = math.log(high-low+1,2)

print("\n\tYou have only",round(chance),"Chances to guess the integer!!\n")

count = 0

while count < chance:
  count += 1
  guess = int(input("Guess a number : "))

  if num == guess:
    print("Congratulations!, You guessed it correctly in ",count," try")
    break

  elif num > guess:
    print("Ohh :( , Your guess is too small")
  elif num < guess:
    print("Ohh :( , Your guess is too big")

if count != chance:
  print("The number was : %d"%num)
  print("\t Better Luck next time! :(")

